In [1]:
file = open("student.txt","r")
data = file.read()

print (data)

Pinkee
Manvi
Arushi
Aditi


In [2]:
file = open("student.txt","r")
data =file.close()

print(data)

None


In [3]:
with open("student.txt", "r") as file:
    data = file.read()
    print(data)

Pinkee
Manvi
Arushi
Aditi


In [3]:
class students:
    pass

In [9]:
class students:
    def display (self):
       print("welcome to python")
        
s1 = students()
s1.display()


welcome to python


In [5]:
class students:
    def display (self):
         print("welcome to python")

s1 = students()
s1.display()

s2 = students()
s2.display()

s3 = students()
s3.display()

welcome to python
welcome to python
welcome to python


In [6]:
class students:
    def display (self):
     print("Name - Pinkee")
     print("Roll no. 56")

s1 = students()
s1.display()

Name - Pinkee
Roll no. 56


In [13]:
class Student:
    
    def display(self):
        print("Student Name:",self.name)
        print("Age:",self.age)
        print("Rollno:",self.rollno)
        
s1=Student()
s2=Student()

s1.name = "Saumya"
s1.age = "33"
s1.rollno = "60"

s2.name = "Jennie"
s2.age = "25"
s2.rollno = "1"

s1.display()
s2.display()
    

Student Name: Saumya
Age: 33
Rollno: 60
Student Name: Jennie
Age: 25
Rollno: 1


In [14]:
class Student:
    
    def display(self):
        print("Student Name:",self.name)
        print("Age:",self.age)
        print("Rollno:",self.rollno)
        
s1=Student()
s2=Student()

s1.name = "J Hope"
s1.age = "33"
s1.rollno = "60"

s2.name = "RM"
s2.age = "3"
s2.rollno = "99"

s1.display()
s2.display()

Student Name: J Hope
Age: 33
Rollno: 60
Student Name: RM
Age: 3
Rollno: 99


In [15]:
class Student:
    def __init__(self, name, roll_no, course, branch):
        self.name = name
        self.roll = roll_no
        self.course = course
        self.branch = branch

    def display(self):
        print("Welcome to Python")
        print(f"Name: {self.name}")
        print(f"Roll no.: {self.roll}")
        print(f"Course: {self.course}")
        print(f"Branch: {self.branch}")
        print("-" * 20) 
        

s1 = Student("Ayukt Yadav", 26, "B.Tech", "Information Technology")
s2 = Student("Rahul Sharma", 30, "B.Tech", "Computer Science")

s1, s2 = s2, s1

s1.display()
s2.display()

Welcome to Python
Name: Rahul Sharma
Roll no.: 30
Course: B.Tech
Branch: Computer Science
--------------------
Welcome to Python
Name: Ayukt Yadav
Roll no.: 26
Course: B.Tech
Branch: Information Technology
--------------------


In [2]:
# Parent Class (Base Class)

class Person:

    def __init__(self, name, age):
        self.name = name
        self.age = age

    def show_person(self):
        print("Name :", self.name)
        print("Age  :", self.age)


# Child Class (Derived Class)

class Student(Person):

    def __init__(self, name, age, roll_no, marks):
        # Call Parent Constructor
        super().__init__(name, age)

        # Child Class Variables
        self.roll_no = roll_no
        self.marks = marks

    def show_student(self):
        print("Roll Number :", self.roll_no)
        print("Marks       :", self.marks)


# Create Object

student1 = Student("Aryaan", 20, 101, 92)


# Display Data

print("Student Information")
print("--------------------")

student1.show_person()      # Parent Class Method
student1.show_student()     # Child Class Method

Student Information
--------------------
Name : Aryaan
Age  : 20
Roll Number : 101
Marks       : 92


In [1]:
numbers = [10, 20, 40, 40, 30]
unique_numbers = list(set(numbers))
unique_numbers.sort()
print(unique_numbers[-2])

30


In [1]:
import keyword

print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [3]:
a = 0.1
b = 0.2
sum = a+b
print (sum)

0.30000000000000004


In [1]:
a = (0.1+0.2==0.3)
print(a)

False


In [4]:
import numpy as np
a = np.array([10,20,30,40])
print(a)

[10 20 30 40]


In [5]:
a = np.array([1.2,3.5,4.5,2.3])
print(a)

[1.2 3.5 4.5 2.3]


In [6]:
a = np.array(["Apple","Banana","Mango"])
print (a)

['Apple' 'Banana' 'Mango']


In [7]:
b = np.array(["John","Manish","Shivi"])
print(b)

['John' 'Manish' 'Shivi']


In [8]:
import numpy as np
a = np.array([1,3,6,5])
print(a.ndim)

1


In [13]:

a = np.array([[1,3],[3,7]])
print(a.ndim)

2


In [14]:
a = np.array([
    [[1,2,4,]],
    [[6,7,9,]],
    [[8,9,2,]],
])
print(a.ndim)

3


In [15]:
a = np.array([[1,2,3,],[5,7,9,]])
print(a.shape)

(2, 3)


In [18]:
a = np.array([
    [1,4,7],
    [2,9,6],
])
print (a.size)

6


In [19]:
a = np.array([2,6,9,8,7,])
print(a.dtype) 

int32


In [25]:
a = np.array([
    [3,8,9],
    [7,9,2]
])

print("Array:", a)
print("Data Type:" ,a.dtype)
print("Size:", a.size)
print("Shape:", a.shape)
print("Dimension:", a.ndim)


Array: [[3 8 9]
 [7 9 2]]
Data Type: int32
Size: 6
Shape: (2, 3)
Dimension: 2


In [26]:
a = np.array([3,6,8,9,])
print(a)

[3 6 8 9]


In [2]:
import numpy as np
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
a = np.full((3,4),4)
print(a)

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [6]:
a = np.full((5,7),7)
print(a)

[[7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]]


In [7]:
a = np.empty((2,2))
print(a)

[[1. 1.]
 [1. 1.]]


In [8]:
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
a = np.arange(0,20,2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18]


In [11]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [12]:
b = a.reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [16]:
a = np.arange(12)

b = a.reshape(3,4)

print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
a = np.array([[1,2],[3,4]])
print(a.flatten())

[1 2 3 4]


In [18]:
a = np.array([10,30,50,70,])
print(a[0])

10


In [21]:
a = np.array([30,60,90,120])
print(a[2])
print(a[3])

90
120


In [20]:
a = np.array([45,89,96,90])
print(a[-1])

90


In [30]:
a = np.array([
    [[6,7,8]],
    [[9,5,3]],
])
print(a)
print(a.size)
print(a.shape)
print(a.dtype)
print(a.ndim)

[[[6 7 8]]

 [[9 5 3]]]
6
(2, 1, 3)
int32
3


In [35]:
import numpy as np
a = np.zeros((3,4))
b = np.full((3, 4), 4)

print(a)
print(b)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [36]:
a = np.array([
    [[4,7,8]],
    [[2,9,5]],
    [[5,9,1]],
])

print(a.size)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.flatten)






      

      

9
3
(3, 1, 3)
9
int32
<built-in method flatten of numpy.ndarray object at 0x35b5de0>


In [40]:
a = np.array([10,20,30,40,50])
print(a[1:4])

[20 30 40]


In [41]:
a = np.array([10,20,30])
b = np.array([1,2,3])
print(a+b)

[11 22 33]


In [42]:
a = np.array([34,89,96])
b = np.array([13,56,87])
print(a-b)

[21 33  9]


In [43]:
a = np.array([34,98,56])
b = np.array([2,6,9])
print(a*b)

[ 68 588 504]


In [44]:
a = np.array([55,99,66])
b = np.array([5,9,6])
print(a/b)

[11. 11. 11.]


In [46]:
a = np.arange(1,20)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [48]:
a = np.zeros((4,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [49]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
import numpy as np

a = np.arange(12)
b = a.reshape([3,4])

print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [59]:
a = np.array([23,89,65,12,10])
mean = np.mean(a)
print(mean)

39.8


In [60]:
a = np.array([45,98,30,60])
a.sort()
print(a)

[30 45 60 98]


In [61]:
a = np.array([98,45,23,12,67])
reverse = True
print(a)

[98 45 23 12 67]


In [62]:
a = np.array([12,14,16,18,10])
print("Average:",a.mean())
print("Median:",np.median(a))
print("Standard Deviation:",np.std(a))

Average: 14.0
Median: 14.0
Standard Deviation: 2.8284271247461903


In [1]:
import numpy as np
a = np.array([1,4,9,16])
print(np.sqrt(a))

[1. 2. 3. 4.]


In [2]:
#Universal Operators
a = np.array([1,4,9,16,25,36])
print(np.abs(a))
print(np.sqrt(a))
print(np.exp(a))
print(np.log(a))
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[ 1  4  9 16 25 36]
[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]
[0.         1.38629436 2.19722458 2.77258872 3.21887582 3.58351894]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175 -0.99177885]
[ 0.54030231 -0.65364362 -0.91113026 -0.95765948  0.99120281 -0.12796369]
[ 1.55740772  1.15782128 -0.45231566  0.30063224 -0.13352641  7.75047091]


In [5]:
a = np.array([25,36,49,64,81])
print(np.sqrt(a))
print(np.abs(a))
print(np.exp(a))
print(np.log(a))
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[5. 6. 7. 8. 9.]
[25 36 49 64 81]
[7.20048993e+10 4.31123155e+15 1.90734657e+21 6.23514908e+27
 1.50609731e+35]
[3.21887582 3.58351894 3.8918203  4.15888308 4.39444915]
[-0.13235175 -0.99177885 -0.95375265  0.92002604 -0.62988799]
[ 0.99120281 -0.12796369  0.30059254  0.39185723  0.77668598]
[-0.13352641  7.75047091 -3.17290855  2.34786031 -0.81099442]


In [6]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [7]:
a = np.array([1,2,3])
b = a.view()
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [8]:
#Boolean Filtering
marks = np.array([45,50,60,65,90])
print(marks>50)


[False False  True  True  True]


In [9]:
#Boolean Filtering
marks = np.array([60,50,10,30,20])
print(marks<50)

[False False  True  True  True]


In [10]:
a = np.array([1,2,3])
print(a+10)

[11 12 13]


In [12]:
matrix = np.array([[1,2],[3,4]])
print(matrix*5)

[[ 5 10]
 [15 20]]


In [13]:
marks = np.array([65,72,85,90,75])
print("Average:",np.mean(marks))
print("Highest:",np.max(marks))
print("Lowest:",np.min(marks))

Average: 77.4
Highest: 90
Lowest: 65


In [17]:
import numpy as np

np.random.seed(42)
salaries = np.random.randint(30000, 120000, size=50)

new_salaries = salaries * 1.05

print("New Salaries after 5% Increment:\n", np.round(new_salaries, 2))
print("Employee Salaries:\n", salaries)
print("-----------------------------------")
print("Mean (Average) Salary:", np.mean(salaries))
print("Maximum Salary:       ", np.max(salaries))
print("Minimum Salary:       ", np.min(salaries))

New Salaries after 5% Increment:
 [ 48084.75  32403.   112161.    89130.3   38078.25 118005.3   70553.7
 123372.9   77837.55  94776.15  48324.15  74644.5  102082.05  99561.
  32307.45  94221.75  97602.75  99671.25 102867.45  37076.55 118759.2
  87892.35 121070.25  61627.65 107028.6   58440.9  120201.9   50852.55
  34384.35  93607.5  100511.25 120386.7   69061.65 102306.75  91230.3
 101643.15  64628.55  43463.7  104046.6   35584.5   75186.3  115539.9
 123178.65  42658.35  40731.6  109167.45  76651.05 111879.6   56591.85
 103055.4 ]
Employee Salaries:
 [ 45795  30860 106820  84886  36265 112386  67194 117498  74131  90263
  46023  71090  97221  94820  30769  89735  92955  94925  97969  35311
 113104  83707 115305  58693 101932  55658 114478  48431  32747  89150
  95725 114654  65773  97435  86886  96803  61551  41394  99092  33890
  71606 110038 117313  40627  38792 103969  73001 106552  53897  98148]
-----------------------------------
Mean (Average) Salary: 78745.34
Maximum Salary:    

In [18]:
#Random Numbers
a = np.array([4,7,9])
print(np.random.rand())

0.230893825622149


In [23]:
#Random Integers
a = np.array([6,70,9])
print(np.random.randint(6,70,9))

[33 52 65 12 49 66 13 52 40]


In [25]:
#Random Matrix
a = np.array([5,80,7])
print(np.random.randint(1,50,(3,4)))

[[14 17 36 40]
 [ 4  2  6 42]
 [ 4 29 18 26]]
